In [2]:
import numpy as np

<h3> Question 1 </h3>

In [14]:
# (a)

arr1= np.linspace(0,1, num=10, endpoint=False)  #revisit this
print (arr1)
print("\n")

# (b)
arr1 = np.zeros(10, dtype=int)
arr1[[i for i in range(len(arr)) if i%2!=0]]=1
print(arr1)
print("\n")

# (c)
arr1 = np.random.random(10)
print(arr1) # displays arr1
print(arr1[np.argmax(arr1)]) # displays maximum value in arr1
arr1[np.argmax(arr1)]=0
print(arr1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0 1 0 1 0 1 0 1 0 1]


[0.52759085 0.04756659 0.31059636 0.13947277 0.51600296 0.78855524
 0.48085316 0.22694605 0.22436237 0.43157891]
0.7885552403963771
[0.52759085 0.04756659 0.31059636 0.13947277 0.51600296 0.
 0.48085316 0.22694605 0.22436237 0.43157891]


<h3>Question 2</h3>

In [30]:
# (a)
even_nums = np.arange(30, 6005)

# (b)
print("There are ",even_nums.size," elements in even_nums")

# (c)
even_nums_desc = even_nums[::-1]   
even_nums_desc[[i for i in range (10)]]

# (d)
indices = even_nums%4==0   
even_nums[indices]
print(even_nums[indices].size)

# (e)
arr1 = np.array([2,5,1.8,7,1.5,4,3.4])
print(np.sqrt(arr1))


There are  5975  elements in even_nums
1494
[1.41421356 2.23606798 1.34164079 2.64575131 1.22474487 2.
 1.84390889]


<h3>Question 3</h3>

In [7]:
# (a)
A = np.array([[1,3,2,6],[3,5,0,7],[2,0,4,8],[4,1,9,2]])
detA = np.linalg.det(A)
print(detA)
invA = np.linalg.inv(A)
print(invA)
print("\n")

# (b)
B = np.array([[0,2,1,4],[-2,0,-3,5],[-1,3,0,7],[6,4,3,2]])
print(A @ B)
print("\n")

# (c)
C = np.copy(A)
C[:,2] = np.max(B, axis=0)
print(C)
print("\n")

# (d)
print(A[[1,3],:]) # for row 2 and 4 using combined indexing
print("\n")

# (e)
print(A[[0,2,3],2]) # for row 1,2 and 4 using combined indexing
print("\n")

#(f)
print(np.array([A[i,i] for i in range(len(A))]))
print("\n")

# (g)
print(A[1:3,1:3])
print("\n")

# (h)
D = np.copy(B)
D[[0,3,0,3],[0,0,3,3]]=100  #fancy indexing takes lists or numpy arrays as indicies
print(D)

578.0000000000001
[[-0.60207612  0.34602076  0.12975779  0.07612457]
 [ 0.30795848  0.00692042 -0.24740484  0.04152249]
 [ 0.22491349 -0.15224913 -0.05709343  0.08650519]
 [ 0.03806228 -0.01038062  0.12110727 -0.06228374]]


[[28 32 10 45]
 [32 34  9 51]
 [44 48 26 52]
 [ 1 43  7 88]]


[[1 3 6 6]
 [3 5 4 7]
 [2 0 3 8]
 [4 1 7 2]]


[[3 5 0 7]
 [4 1 9 2]]


[2 4 9]


[1 5 4 2]


[[5 0]
 [0 4]]


[[100   2   1 100]
 [ -2   0  -3   5]
 [ -1   3   0   7]
 [100   4   3 100]]


<h3>Question 4</h3>

In [15]:
# (a)
arr1=np.random.rand(5,6) # revisit this
print(arr1)
print("\n")

# (b)
print(np.mean(arr1))
print("\n")

# (c)
print(np.min(arr1, axis=1))  # minimum value along each row
print(np.max(arr1, axis=0))  #maximum value along each column
print("\n")

# (d)
arr2=10*arr1.astype(np.int16)
print(arr2)
print(arr2.dtype)

[[0.58186736 0.3280659  0.60401897 0.49140599 0.43658544 0.02644702]
 [0.7144255  0.78870985 0.90485795 0.909875   0.4726913  0.54984036]
 [0.11684537 0.81819224 0.58283029 0.62517182 0.93065815 0.26232252]
 [0.54651684 0.46548349 0.20966691 0.18214816 0.66709749 0.97618946]
 [0.73072119 0.68692726 0.93887116 0.80699599 0.28985018 0.97725044]]


0.5874176537154769


[0.02644702 0.4726913  0.11684537 0.18214816 0.28985018]
[0.73072119 0.81819224 0.93887116 0.909875   0.93065815 0.97725044]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
int16


<h3>Question 5</h3>

In [11]:
# (a)
arr1 = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16],[31,32,33,34,35,36],[41,42,43,44,45,46],[51,52,53,54,55,56],[61,62,63,64,65,66]])
print(arr1)
print("\n")

# (b)
print(arr1[:,1])
print("\n")

# (c)
print(arr1[0::2,0::3])
print("\n")

# (d)
print(arr1[1,2:5])
print("\n")

# (e)
print(arr1[3:5,4:6])

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]


[ 2 12 32 42 52 62]


[[ 1  4]
 [31 34]
 [51 54]]


[13 14 15]


[[45 46]
 [55 56]]


<h3>Question 6</h3>

In [74]:
# (a)
scores=np.random.randint(101, size=(100, 3), dtype=np.int8)
print(scores)
print("\n")

# (b)
sn = np.arange(1,101, dtype=np.int8)
print(sn)
print("\n")

# (c)
sn = sn[np.newaxis,:]   # increase the dimension of the sn array from 1D to 2D
snscores = np.hstack((sn.T,scores))
print(snscores[0:4,0:4])

# (d)
np.savetxt('scores.csv', snscores, fmt='%i')
print("\n")

# (e)
marks = np.genfromtxt('scores.csv', delimiter=' ',dtype=np.int8)
print(marks.shape)
print("\n")

# (f)
print("{:<7}".format('  '), end=' ')
print("{}".format('Test 1'), end=' ')
print("{}".format('Test 2'), end=' ')
print("{}".format('Test 3'))

print("Min {:<3}".format(''), "{:5.2f}".format(np.min((marks), axis=0)[1]), "{:5.2f}".format(np.min((marks), axis=0)[2]), "{:5.2f}".format(np.min((marks), axis=0)[3]))
print("Max {:<4}".format(''), "{:5.2f}".format(np.max((marks), axis=0)[1]), "{:5.2f}".format(np.max((marks), axis=0)[2]),"{:5.2f}".format(np.max((marks), axis=0)[3]))
print("Average {:<0}".format(''), "{:5.2f}".format(np.mean((marks), axis=0)[1]),"{:5.2f}".format(np.mean((marks), axis=0)[2]),"{:5.2f}".format(np.mean((marks), axis=0)[3]))
print("Std {:<4}".format(''),"{:5.2f}".format(np.std((marks), axis=0)[1]),"{:5.2f}".format(np.std((marks), axis=0)[2]),"{:5.2f}".format(np.std((marks), axis=0)[3]))

[[ 37  40  50]
 [  7  85  14]
 [ 81  80  79]
 [  7  67  44]
 [ 43  51  82]
 [ 10  45  30]
 [  7  82  58]
 [ 24   4  40]
 [ 66  23  31]
 [  2   4  56]
 [ 99  97  93]
 [ 89  21  24]
 [ 93  53  89]
 [ 31  36  77]
 [ 39   3  45]
 [ 33  47  15]
 [ 63  95  37]
 [ 64  99  97]
 [ 65  81  66]
 [ 86  88  77]
 [ 11  63  78]
 [ 67  73  91]
 [ 61  54  88]
 [  1  38  31]
 [ 39  17  19]
 [ 13  16   9]
 [ 33  55  47]
 [ 86  67  58]
 [ 61  47  71]
 [ 87  10  13]
 [ 29  41  67]
 [ 37  45  19]
 [ 28  52  37]
 [  7  84  38]
 [ 30  50  66]
 [ 30  82  24]
 [ 59  44  97]
 [ 14  11  40]
 [  3  32  89]
 [ 38  24  85]
 [ 11  67  25]
 [ 12  29  55]
 [ 26  42  49]
 [  0  64  95]
 [ 59  76  19]
 [ 64  72  69]
 [ 52  30   7]
 [  5  81  25]
 [ 94  63   2]
 [ 78  59  59]
 [ 17  21  54]
 [ 82  51  12]
 [ 34  16   3]
 [ 85  66  85]
 [ 65  76  56]
 [  9  39  28]
 [  5  79  20]
 [ 93  19  15]
 [ 93  44  83]
 [ 25  16  13]
 [ 37  40  61]
 [ 97  55  22]
 [ 68  48  90]
 [ 37  51  39]
 [ 22  54  71]
 [ 22   3  69]
 [ 34   2 

<h3>Question 7</h3>