In [10]:
import numpy as np

<h3> Question 1 </h3>

In [4]:
# (a)

arr1= np.linspace(0,1, num=10, endpoint=False) #revisit this
print (arr1)
print("\n")

# (b)
arr1 = np.zeros(10, dtype=int)
arr1[[i for i in range(len(arr1)) if i%2!=0]]=1
print(arr1)
print("\n")

# (c)
arr1 = np.random.random(10)
print(arr1) # displays arr1
print(arr1[np.argmax(arr1)]) # displays maximum value in arr1
arr1[np.argmax(arr1)]=0
print(arr1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0 1 0 1 0 1 0 1 0 1]


[0.97244449 0.43659069 0.73438757 0.84395345 0.88115436 0.59831114
 0.1053912  0.27957863 0.48542936 0.52204519]
0.9724444944529367
[0.         0.43659069 0.73438757 0.84395345 0.88115436 0.59831114
 0.1053912  0.27957863 0.48542936 0.52204519]


<h3>Question 2</h3>

In [7]:
# (a)
even_nums = np.arange(30, 6005, 2)

# (b)
print("There are ",even_nums.size," elements in even_nums")

# (c)
even_nums_desc = even_nums[::-1]   
print(even_nums_desc[[i for i in range (10)]])

# (d)
indices = even_nums%4==0   
even_nums[indices]
print(even_nums[indices].size)

# (e)
arr1 = np.array([2,5,1.8,7,1.5,4,3.4])
print(np.sqrt(arr1))


There are  2988  elements in even_nums
[6004 6002 6000 5998 5996 5994 5992 5990 5988 5986]
1494
[1.41421356 2.23606798 1.34164079 2.64575131 1.22474487 2.
 1.84390889]


<h3>Question 3</h3>

In [9]:
# (a)
A = np.array([[1,3,2,6],[3,5,0,7],[2,0,4,8],[4,1,9,2]])
detA = np.linalg.det(A)
print(detA)
invA = np.linalg.inv(A)
print(invA)
print("\n")

# (b)
B = np.array([[0,2,1,4],[-2,0,-3,5],[-1,3,0,7],[6,4,3,2]])
print(A @ B)
print("\n")

# (c)
C = np.copy(A)
C[:,2] = np.max(B, axis=0)
print(C)
print("\n")

# (d)
print(A[[1,3],:]) # for row 2 and 4 using combined indexing
print("\n")

# (e)
print(A[[0,2,3],2]) # for row 1,2 and 4 and column 3 using combined indexing
print("\n")

#(f)
print(np.array([A[i,i] for i in range(int(np.sqrt(A.size)))]))
print("\n")

# (g)
print(A[1:3,1:3])
print("\n")

# (h)
D = np.copy(B)
D[[0,3,0,3],[0,0,3,3]]=100  #fancy indexing takes lists or numpy arrays as indicies
print(D)

578.0000000000001
[[-0.60207612  0.34602076  0.12975779  0.07612457]
 [ 0.30795848  0.00692042 -0.24740484  0.04152249]
 [ 0.22491349 -0.15224913 -0.05709343  0.08650519]
 [ 0.03806228 -0.01038062  0.12110727 -0.06228374]]


[[28 32 10 45]
 [32 34  9 51]
 [44 48 26 52]
 [ 1 43  7 88]]


[[1 3 6 6]
 [3 5 4 7]
 [2 0 3 8]
 [4 1 7 2]]


[[3 5 0 7]
 [4 1 9 2]]


[2 4 9]


[1 5 4 2]


[[5 0]
 [0 4]]


[[100   2   1 100]
 [ -2   0  -3   5]
 [ -1   3   0   7]
 [100   4   3 100]]


<h3>Question 4</h3>

In [11]:
# (a)
arr1=np.random.rand(5,6) # revisit this
print(arr1)
print("\n")

# (b)
print(np.mean(arr1))
print("\n")

# (c)
print(np.min(arr1, axis=1))  # minimum value along each row
print(np.max(arr1, axis=0))  #maximum value along each column
print("\n")

# (d)
arr2=10*arr1
print(arr2.astype(np.int16))

[[0.04284878 0.71567997 0.56166086 0.34205513 0.31405967 0.97326699]
 [0.67277907 0.44165822 0.191693   0.24261923 0.67361361 0.07051362]
 [0.10059784 0.5125755  0.05318741 0.87767499 0.65976202 0.80077735]
 [0.61537415 0.97837151 0.22480711 0.23945462 0.78469172 0.46704915]
 [0.68147971 0.09059729 0.48060838 0.59969247 0.67969437 0.86583933]]


0.4984894358329669


[0.04284878 0.07051362 0.05318741 0.22480711 0.09059729]
[0.68147971 0.97837151 0.56166086 0.87767499 0.78469172 0.97326699]


[[0 7 5 3 3 9]
 [6 4 1 2 6 0]
 [1 5 0 8 6 8]
 [6 9 2 2 7 4]
 [6 0 4 5 6 8]]


<h3>Question 5</h3>

In [6]:
# (a)
arr1 = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16],[31,32,33,34,35,36],[41,42,43,44,45,46],[51,52,53,54,55,56],[61,62,63,64,65,66]])
print(arr1)
print("\n")

# (b)
print(arr1[:,1])
print("\n")

# (c)
print(arr1[0::2,0::3])
print("\n")

# (d)
print(arr1[1,2:5])
print("\n")

# (e)
print(arr1[3:5,4:6])

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]


[ 2 12 32 42 52 62]


[[ 1  4]
 [31 34]
 [51 54]]


[13 14 15]


[[45 46]
 [55 56]]


<h3>Question 6</h3>

In [16]:
# (a)
scores=np.random.randint(101, size=(100, 3), dtype=np.int8)
print(scores)
print("\n")

# (b)
sn = np.arange(1,101, dtype=np.int8)
print(sn)
print("\n")

# (c)
sn = sn[np.newaxis,:]   # increase the dimension of the sn array from 1D to 2D
snscores = np.hstack((sn.T,scores))
print(snscores[0:4,0:4])

# (d)
np.savetxt('scores.csv', snscores, fmt='%i')
print("\n")

# (e)
marks = np.genfromtxt('scores.csv', delimiter=' ',dtype=np.int8)
print(marks.shape)
print("\n")

# (f)
print("{:<7}".format('  '), end=' ')
print("{}".format('Test 1'), end=' ')
print("{}".format('Test 2'), end=' ')
print("{}".format('Test 3'))

print("Min {:<3}".format(''), "{:5.2f}".format(np.min((marks), axis=0)[1]), "{:5.2f}".format(np.min((marks), axis=0)[2]), "{:5.2f}".format(np.min((marks), axis=0)[3]))
print("Max {:<4}".format(''), "{:5.2f}".format(np.max((marks), axis=0)[1]), "{:5.2f}".format(np.max((marks), axis=0)[2]),"{:5.2f}".format(np.max((marks), axis=0)[3]))
print("Average {:<0}".format(''), "{:5.2f}".format(np.mean((marks), axis=0)[1]),"{:5.2f}".format(np.mean((marks), axis=0)[2]),"{:5.2f}".format(np.mean((marks), axis=0)[3]))
print("Std {:<4}".format(''),"{:5.2f}".format(np.std((marks), axis=0)[1]),"{:5.2f}".format(np.std((marks), axis=0)[2]),"{:5.2f}".format(np.std((marks), axis=0)[3]))
print("\n")

# (g)
weight = np.array([0.2, 0.3, 0.5])
newscores = np.multiply(marks[:, 1:4], weight)
OverallScore = np.sum(newscores, axis=1)

print("Grade", "Overall Score")
print('A     ', OverallScore[(OverallScore >= 70)].size)
print('B+    ', OverallScore[((60 <= OverallScore) & (OverallScore < 70))].size)
print('B     ', OverallScore[((50 <= OverallScore) & (OverallScore < 60))].size)
print('C     ', OverallScore[((40 <= OverallScore) & (OverallScore < 50))].size)
print('D     ', OverallScore[((35 <= OverallScore) & (OverallScore < 40))].size)
print('E     ', OverallScore[((0 <= OverallScore) & (OverallScore < 35))].size)
print("\n")

# (h)
maximum = np.max(OverallScore)
print(maximum)

i = np.argwhere(OverallScore == maximum)
print("Maximum is at student no(s):", i)


[[ 15  85  82]
 [ 92  55  23]
 [ 94  15  70]
 [ 65  63  56]
 [ 24  38  90]
 [ 92  10  46]
 [ 33  99  15]
 [ 10  79  59]
 [ 79   2  13]
 [ 81  57  80]
 [ 90  22  34]
 [ 73  22  21]
 [ 24  89  82]
 [ 25  16  18]
 [ 60  64  86]
 [ 69  47  85]
 [ 43  45  58]
 [ 24  42  90]
 [ 75  74  40]
 [ 38  28   3]
 [ 68  72  34]
 [ 37  83   6]
 [ 86  87  92]
 [ 54  18  24]
 [ 12  20  54]
 [ 57  57  42]
 [ 15  30   5]
 [ 29  83  58]
 [100  15  85]
 [ 60  74  37]
 [ 21  67  33]
 [ 47  23  43]
 [ 12   2  30]
 [ 34  64  36]
 [ 26  97  21]
 [  2   1   5]
 [ 71  94  92]
 [ 45  10  78]
 [ 99  90  42]
 [ 30  25  78]
 [ 65  95  85]
 [ 85  68   7]
 [ 68  10  46]
 [ 97   6  90]
 [ 40  29  81]
 [ 43  20  12]
 [ 93  91  92]
 [  1  36  82]
 [ 89  80  21]
 [ 82  94   6]
 [ 19  82  65]
 [ 95  39  17]
 [ 42  88  93]
 [ 49  61  17]
 [ 66  93  58]
 [ 98   8  61]
 [ 58  22  27]
 [  7  42  75]
 [ 99   1  14]
 [ 86  88   0]
 [ 12  70   0]
 [ 16  22  98]
 [ 93  30  68]
 [ 67  45  33]
 [ 73  76  92]
 [ 12  25   3]
 [ 93  80 

<h3>Question 7</h3>

In [21]:
# (a)
arr1 = np.array([[0,1,2,3,4,5,6,7,8,9,10,11,12],[1980,300,200,100,50,0,10,75,60,90,150,325,400],[1981,290,220,110,40,5,15,80,90,85,160,290,350],[1982,320,230,90,25,10,5,90,80,95,155,300,340],[1983,280,190,105,15,20,10,85,95,100,140,310,320]])
print(arr1)
print(np.max(arr1[2,1:]))
print(np.min(arr1[2,1:]))
print(np.mean(arr1[2,1:]))
print("\n")

# (b)
year = arr1[(np.argmax(arr1[1:,5])+1), 0]
print(year)
print(np.amax(arr1[1:,5])) #returns the maximum value for month May
print("\n")

# (c)
print(arr1[1:4,5:11])

# (d)
print(np.max(arr1[1:,1:]))
print(np.min(arr1[1:,1:]))

# (e)
arr1[4,1:].sort()
arr2 = arr1[4,1:]
print(arr2[::-1])

[[   0    1    2    3    4    5    6    7    8    9   10   11   12]
 [1980  300  200  100   50    0   10   75   60   90  150  325  400]
 [1981  290  220  110   40    5   15   80   90   85  160  290  350]
 [1982  320  230   90   25   10    5   90   80   95  155  300  340]
 [1983  280  190  105   15   20   10   85   95  100  140  310  320]]
350
5
144.58333333333334


1983
20


[[  0  10  75  60  90 150]
 [  5  15  80  90  85 160]
 [ 10   5  90  80  95 155]]
400
0
[320 310 280 190 140 105 100  95  85  20  15  10]
